# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 364ab509ed2e231072bbf4ff7ddadb35bfaf4739f35eeba445299e77fccf96e98e5d30e30877313cfe88bc5fbaf031ed50163ef693e424da7da8a645beb5e322

test:
  secret_key_base: 0b2009d84bd93cb133dec9095d09f6fa8e3d94f2e66089341f32fa9d092c06a2524daa28560b00829e8c49d6143b75626a6f95616fe3a4bebe6d84582b1ea1d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
